site_name: VK Quick
site_description: Async python package for creating VK chat bots
repo_name: vkquick
repo_url: https://github.com/Rhinik/vkquick_old2

remote_branch: master

google_analytics: ["UA-172364682-1", "vkquick_old2.github.io"]

nav:
    - Test: build/markdown/vkquick.md

theme:
    name: material
    language: ru
    font:
        text: Ubuntu
        code: Monaco
    palette:
        primary: blue grey
        accent: teal

markdown_extensions:
    - toc:
        permalink: true
    - markdown.extensions.codehilite:
        guess_lang: false
    - admonition
    - codehilite
    - extra
    - pymdownx.superfences:
        custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format ''
    - pymdownx.tabbed
    - pymdownx.details
    - pymdownx.tilde
    - admonition
    - codehilite
    - mkautodoc

extra_css:
    - css/termynal.css
    - css/custom.css

extra_javascript:
    - js/termynal.js
    - js/custom.js
