[tool.poetry]
name = "vkquick"
version = "0.1.0"
description = "Package for quick writing vk chat bots"
authors = ["Kurbatov Yan <deknowny@gmail.com>"]
readme = "README.md"
keywords = [
    "vk", "async", "bots", "quick"
]

[tool.poetry.dependencies]
python = "^3.8"
click = "^7.1.2"
attrdict = "^2.0.1"
aiohttp = "^3.6.2"
watchdog = "^0.10.2"
colorama = "^0.4.3"
toml = "^0.10.1"
pygments = "^2.6.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[tool.poetry.scripts]
bot = "vkquick.console:bot"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
