[tool.poetry]
name = "vkquick"
version = "1.0.0a0"
description = "Package for quick writing vk chat bots"
license = "MIT"
homepage = "https://github.com/Rhinik/vkquick"
documentation = "https://vkquick.github.io"
authors = ["Kurbatov Yan <deknowny@gmail.com>"]
readme = "README.md"
keywords = [
    "vk", "async", "bots", "quick", "api"
]
classifiers = [
    "Environment :: Console",
    "Framework :: AsyncIO",
    "Intended Audience :: Developers",
    "Natural Language :: Russian",
    "Topic :: Documentation",
    "Topic :: Software Development :: Code Generators",
    "Typing :: Typed",
    "Topic :: Utilities"
]


[tool.poetry.dependencies]
python = "^3.8"
watchdog = "^0.10.2"
colorama = "^0.4.3"
pygments = "^2.6.1"
cleo = "^0.8.1"
orjson = { version = "^3.3.1", optional = true}


[tool.poetry.dev-dependencies]
mkdocs-material = "^5.4.0"
mkdocs = "^1.1.2"
pytest-asyncio = "^0.14.0"
black = "^19.10b0"
sqlalchemy = "^1.3.18"
pytest = "^6.1.0"
pytest-cov = "^2.10.1"
pylint = "^2.6.0"

[tool.poetry.urls]
"VK group" = "https://vk.com/vkquick"
"Help chat" = "https://vk.me/join/AJQ1dzLqwBeU7O0H_oJZYNjD"

[tool.black]
line-length = 78

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
